[toolchain]
bpf = "bpfel-unknown-unknown"

[features]
resolution = true
skip-lint = false
seeds = true


[programs.localnet]
promise_keeper = "3BsTL53Aab3un682i8sjPeyQSgPMhXmwM3aDv7Py3gR9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
