[toolchain]
bpf = "bpfel-unknown-unknown"

[features]
resolution = true
skip-lint = false
seeds = true


[programs.localnet]
promise_keeper = "AkxggcMGrz1PQYCqUnyR8PxiZMgKp8WsND1W9Sm59qsJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --test-threads=1" # here must be 1 thread due to manual computing tasks PDA depending on tasks counter value
